#!/usr/bin/env bash

# +-----+
# | Zsh |
# +-----+

# Zsh Directory Stack, track the last 9 visited directories and go back by the number
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack

# +----------------+
# | Homebrew x86_64|
# +----------------+
alias ibrew="arch -x86_64 /usr/local/bin/brew"

# +----+
# | cp |
# +----+

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

# +--------+
# | Neovim |
# +--------+

# alias vim='nvim'
# alias vi='nvim'

# +-----+
# | eza |
# +-----+

alias ll="eza -l -g --icons"
alias ls="eza --icons"
