#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export DOTFILES="$HOME/dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/.local/share"
export XDG_STATE_HOME="$XDG_CONFIG_HOME/.local/state"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# other software
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonrc.py"

# pyenv
export PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

# Gradle
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

# fzf
# TODO: fzf
